/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package io.vov.vitamio;

public final class R {
    public static final class raw {
    	public static final int libarm= com.example.vitamioplayeruserdemo.R.raw.libarm;
    }
}
